server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:bot;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

bot:
  slack:
    botToken: ${SLACK_BOT_TOKEN:test-bot-token}
    signingSecret: ${SLACK_BOT_SIGN_SECRET:test-signing-secret}
  jira:
    clientId: ${JIRA_CLIENT_ID:test-client-id}
    clientSecret: ${JIRA_CLIENT_SECRET:test-client-secret}
    redirectUri: ${JIRA_REDIRECT_URI:http://localhost:8080/jira/oauth2/callback}
    scopes: ${JIRA_SCOPES:read:jira-user read:jira-work write:jira-work offline_access}
    authorizeUrl: ${JIRA_AUTHORIZE_URL:https://auth.atlassian.com/authorize}
    tokenUrl: ${JIRA_TOKEN_URL:https://auth.atlassian.com/oauth/token}
    resourcesUrl: ${JIRA_RESOURCES_URL:https://api.atlassian.com/oauth/token/accessible-resources}
  security:
    encryptionKey: ${TOKEN_ENCRYPTION_KEY:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
